### PR TITLE
Add Joke Service and Test

### LINKED ISSUE #6: Add Joke Service and Tests
# Acceptance Criteria:

- [ ] There is <tt>JokeQueryService.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/services` directory.
- [ ] <tt>JokeQueryService.java</tt>  implements a class that make a call to the appropriate API
      and returns the results.
- [ ] There is  <tt>JokeQueryServiceTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/services` directory.
- [ ] The tests in  <tt>JokeQueryServiceTests.java</tt> provide 100% coverage of  <tt>JokeQueryService.java</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/s24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by ylin250**
In this PR, we add an service that wraps the Location API from
https://nominatim.openstreetmap.org/search.php?q={location}&format=json";

Closes #6

### CODE REVIEW

**Comment by Peak1260** [comment]
Can you add the link to your dokku so we can make sure that everything is running properly?

**Comment by ylin250** [comment]
Things... aren't working properly, on localhost yes, on dokku... http://team01.dokku-00.cs.ucsb.edu/swagger-ui/index.html#/joke-controller/getJokesUsingGET

**Comment by crosscountrycoder** [comment]
It's been five days. Did you get it to work on Dokku?

**Review by crosscountrycoder — COMMENTED** [review]
Please make sure the code works on Dokku. Otherwise, looks good to me.

**Pull request closed without merging**
