### PR TITLE
Add University Service and Controller

### PR DESCRIPTION
**Pull request by JUstISAGE**
In this PR, we add an endpoint `/api/zipcode/get` that can be used to get information
about the University, here is the link: http://team01-justisage-dev.dokku-09.cs.ucsb.edu/swagger-ui/index.html

### CODE REVIEW

**Comment by Peak1260** [comment]
Everything is checked and it looks great!

**Comment by crosscountrycoder** [comment]
Checked it and it looks good. (I know it was merged a long time ago but I still need to review it to complete h02)

**Review by Peak1260 — COMMENTED** [review]
LGTM

**Review by Peak1260 — COMMENTED** [review]
LGTM

**Pull request merged**
